version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  test_my_app:
    jobs:
      - path-filtering/filter:
          base-revision: testing
          config-path: .circleci/continue_config.yml
          exclude: |
            docs/.*
            README\.md
            mkdocs\.yml
            .*\.md
            .*\.html
            .*\.js
            .*\.css
          mapping: |
            .* run_tests true
