version: 2.1

parameters:
  run_tests:
    type: boolean
    default: false

orbs:
  win: circleci/windows@5.1.1
  codecov: codecov/codecov@5.4.3

jobs:
  build_and_test:
    parameters:
      python_version:
        type: string
        default: "3.10.11"
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install Python
          # Installs the specific version defined in the matrix
          command: choco install python --version=<< parameters.python_version >> --allow-downgrade -y
      - run:
          name: Check Python Version
          command: python --version
      - run:
          name: Upgrade pip and install core
          # "pip install --upgrade" automatically pulls the latest versions
          command: python -m pip install --upgrade pip wheel numpy cython opencv-python
      - run:
          name: Install vidgear and dependencies
          command: python -m pip install --upgrade .[asyncio] six httpx yt-dlp[default] aiortc
      - run:
          name: Install test dependencies
          command: |
            python -m pip install --upgrade pytest pytest-cov pytest-asyncio m3u8 async-asgi-testclient paramiko mpegdash deffcode
      - run:
          name: Prepare dataset
          shell: bash.exe
          command: |
            chmod +x scripts/bash/prepare_dataset.sh
            bash scripts/bash/prepare_dataset.sh
      - run:
          name: Run tests
          # Generates coverage.xml for the Codecov orb
          command: python -m pytest --verbose --capture=no --cov-report xml:coverage.xml --cov-report term-missing --cov=vidgear vidgear/tests/
      - codecov/upload:
          files: coverage.xml

workflows:
  run_tests:
    when: << pipeline.parameters.run_tests >>
    jobs:
      - build_and_test:
          matrix:
            parameters:
              python_version: ["3.10.11", "3.11.9", "3.12.10", "3.13.13"]
          filters:
            branches:
              only: testing